---
# Implement your Workload deployment tasks here

- name: Make sure project "{{ t_user_project }}" is there
  k8s:
    state: present
    name: "{{ t_user_project }}"
    kind: Project
    api_version: project.openshift.io/v1

- name: Create Catalog Source for use with catalog snapshot
  k8s:
    state: present
    definition: "{{ lookup('template', './templates/catalogsource.j2' ) | from_yaml }}"
  vars:
    namespace: "{{ t_user_project }}"

- name: Assign "{{ t_user }}" as admin
  k8s:
    state: present
    definition: "{{ lookup('template', './templates/rbac.j2' ) }}"
  vars:
    name: "{{ t_user }}"
    namespace: "{{ t_user_project }}"

- name: Install RH SSO operator in {{ t_user_project }}
  k8s:
    state: present
    definition: "{{ lookup('template', './templates/rhsso_operator.j2' ) }}"

- name: Wait until InstallPlan is created
  k8s_info:
    api_version: operators.coreos.com/v1alpha1
    kind: InstallPlan
    namespace: "{{ t_user_project }}"
  register: r_install_plans
  vars:
    _query: >-
      [?starts_with(spec.clusterServiceVersionNames[0], 'rhsso')]
  retries: 30
  delay: 5
  until:
  - r_install_plans.resources | length > 0
  - r_install_plans.resources | to_json | from_json | json_query(_query)

- name: Set InstallPlan Name
  set_fact:
    ocp4_workload_servicemesh_workshop_rhsso_install_plan_name: "{{ r_install_plans.resources | to_json | from_json | json_query(query) }}"
  vars:
    query: >-
      [?starts_with(spec.clusterServiceVersionNames[0], 'rhsso')].metadata.name|[0]

- name: Get InstallPlan
  k8s_info:
    api_version: operators.coreos.com/v1alpha1
    kind: InstallPlan
    name: "{{ ocp4_workload_servicemesh_workshop_rhsso_install_plan_name }}"
    namespace: "{{ t_user_project }}"
  register: r_install_plan

- name: Approve InstallPlan if necessary
  when: r_install_plan.resources[0].status.phase is match("RequiresApproval")
  k8s:
    state: present
    definition: "{{ lookup( 'template', './templates/rhsso_installplan.j2' ) }}"

- name: Get Installed CSV
  k8s_info:
    api_version: operators.coreos.com/v1alpha1
    kind: Subscription
    name: rhsso-operator
    namespace: "{{ t_user_project }}"
  register: r_subscription
  retries: 30
  delay: 5
  until:
  - r_subscription.resources[0].status.currentCSV is defined
  - r_subscription.resources[0].status.currentCSV | length > 0

- name: Wait until CSV is Installed
  k8s_info:
    api_version: operators.coreos.com/v1alpha1
    kind: ClusterServiceVersion
    name: "{{ r_subscription.resources[0].status.currentCSV }}"
    namespace: "{{ t_user_project }}"
  register: r_csv
  retries: 15
  delay: 5
  until:
  - r_csv.resources[0].status.phase is defined
  - r_csv.resources[0].status.phase | length > 0
  - r_csv.resources[0].status.phase == "Succeeded"

- name: Make sure project "{{ t_user_servicemesh_project }}"" is there
  k8s:
    state: present
    name: "{{ t_user_servicemesh_project }}"
    kind: Project
    api_version: project.openshift.io/v1

- name: Assign "{{ t_user }}" as admin
  k8s:
    state: present
    definition: "{{ lookup('template', './templates/rbac.j2' ) }}"
  vars:
    name: "{{ t_user }}"
    namespace: "{{ t_user_servicemesh_project}}"

- name: Make sure to delete any limit ranges in {{ t_user_servicemesh_project }}
  k8s:
    state: absent
    name: "{{ t_user_servicemesh_project }}"
    kind: LimitRange

- name: Create service mesh control plane in {{ t_user_servicemesh_project }}
  k8s:
    state: present
    definition: "{{ lookup('template', './templates/servicemesh_controlplane.j2' ) }}"
  vars:
    namespace: "{{ t_user_servicemesh_project}}"

- name: Wait for Service Mesh Control Plane to finish installation
  k8s_info:
    api_version: maistra.io/v2
    kind: ServiceMeshControlPlane
    name: workshop-install
    namespace: "{{ t_user_servicemesh_project }}"
  register: r_smcp
  retries: 40
  delay: 10
  until:
  - r_smcp.resources[0].status.readiness.components is defined
  - r_smcp.resources[0].status.readiness.components.pending | length == 0
  - r_smcp.resources[0].status.readiness.components.unready | length == 0

- name: Add {{ t_user_project }} as a member to its corresponding service mesh project
  k8s:
    state: present
    definition: "{{ lookup('template', './templates/servicemesh_memberroll.j2' ) }}"
  vars:
    namespace: "{{ t_user_servicemesh_project}}"
    user_namespace: "{{ t_user_project }}"

- name: Wait for Service Mesh Member Roll to configure completely
  k8s_info:
    api_version: maistra.io/v1
    kind: ServiceMeshMemberRoll
    name: default
    namespace: "{{ t_user_servicemesh_project }}"
  register: r_smmr
  retries: 15
  delay: 5
  until:
  - r_smmr.resources[0].spec.members is defined
  - r_smmr.resources[0].spec.members | length > 0

- name: Create network policy to allow traffic into {{ t_user_project }}
  k8s:
    state: present
    definition: "{{ lookup('template', './templates/netpol.j2' ) }}"

## This is hacky, but there's no field in the Service Mesh Control Plane to modify this easily right now
- name: Get Kiali Config Map
  k8s_info:
    api_version: v1
    kind: ConfigMap
    name: kiali
    namespace: "{{ t_user_servicemesh_project }}"
  register: r_kiali_cm

- name: Remove DeploymentConfig from excluded workloads
  set_fact:
    r_kiali_cm_config: "{{ r_kiali_cm.resources[0].data['config.yaml'] | replace('- DeploymentConfig\n', '') }}"

- name: Create new Kiali Config Map
  set_fact:
    r_kiali_cm_new: {'apiVersion': 'v1', 'kind': 'ConfigMap', 'metadata': "{{ r_kiali_cm.resources[0].metadata }}", 'data': {'config.yaml': "{{ r_kiali_cm_config}}"}}

- name: Apply new Config Map
  k8s:
    state: present
    definition: "{{ r_kiali_cm_new | to_yaml }}"

- name: Scale Kiali down
  k8s_scale:
    api_version: v1
    kind: Deployment
    name: kiali
    namespace: "{{ t_user_servicemesh_project }}"
    replicas: 0
    wait: no

- name: Wait for scale down
  k8s_info:
    api_version: v1
    kind: Deployment
    name: kiali
    namespace: "{{ t_user_servicemesh_project }}"
  register: r_kiali_deployment
  retries: 15
  delay: 5
  until:
  - r_kiali_deployment.resources | json_query('[*].status.conditions[?type==`Available`][].status') | select ('match','True') | list | length == 1

- name: Restart Kiali for config map change to take effect
  k8s_scale:
    api_version: v1
    kind: Deployment
    name: kiali
    namespace: "{{ t_user_servicemesh_project }}"
    replicas: 1
    wait: no

- name: Wait for scale up
  k8s_info:
    api_version: v1
    kind: Deployment
    name: kiali
    namespace: "{{ t_user_servicemesh_project }}"
  register: r_kiali_deployment
  retries: 15
  delay: 5
  until:
  - r_kiali_deployment.resources | json_query('[*].status.conditions[?type==`Available`][].status') | select ('match','True') | list | length == 1

# Additional steps for mini workshop

- name: Check if UI was already deployed
  k8s_info:
    api_version: apps.openshift.io/v1
    kind: DeploymentConfig
    name: app-ui
    namespace: "{{ t_user_project }}"
  register: app_deployment

- name: Deploy the app
  command: >-
          oc new-app -f "{{ ocp4_workload_servicemesh_workshop_app_template }}" -n "{{ t_user_project }}" \
            -p APPLICATION_NAME=app-ui \
            -p NODEJS_VERSION_TAG=10 \
            -p GIT_BRANCH=workshop-stable \
            -p GIT_URI=https://github.com/RedHatGov/service-mesh-workshop-code.git \
            -e FAKE_USER=true
  when: app_deployment.resources | length | int < 1

- name: Check if boards was already deployed
  k8s_info:
    api_version: apps.openshift.io/v1
    kind: DeploymentConfig
    name: boards
    namespace: "{{ t_user_project }}"
  register: boards_deployment

- name: Deploy boards
  command: >-
          oc new-app -f "{{ ocp4_workload_servicemesh_workshop_boards_template }}" -n "{{ t_user_project }}" \
            -p APPLICATION_NAME=boards \
            -p NODEJS_VERSION_TAG=10 \
            -p GIT_URI=https://github.com/RedHatGov/service-mesh-workshop-code.git \
            -p GIT_BRANCH=workshop-stable \
            -p DATABASE_SERVICE_NAME=boards-mongodb \
            -p MONGODB_DATABASE=boardsDevelopment
  when: boards_deployment.resources | length | int < 1

- name: Check if context scraper was already deployed
  k8s_info:
    api_version: apps.openshift.io/v1
    kind: DeploymentConfig
    name: context-scraper
    namespace: "{{ t_user_project }}"
  register: context_scraper_deployment

- name: Deploy context scraper
  command: >-
          oc new-app -f "{{ ocp4_workload_servicemesh_workshop_context_scraper_template }}" -n "{{ t_user_project }}" \
            -p APPLICATION_NAME=context-scraper \
            -p NODEJS_VERSION_TAG=10 \
            -p GIT_BRANCH=workshop-stable \
            -p GIT_URI=https://github.com/RedHatGov/service-mesh-workshop-code.git
  when: context_scraper_deployment.resources | length | int < 1

- name: Install gateway config in {{ t_user_project }}
  k8s:
    state: present
    definition: "{{ lookup('template', './templates/gateway.j2' ) }}"

- name: Check if build was created already
  k8s_info:
    api_version: build.openshift.io/v1
    kind: BuildConfig
    name: userprofile-1.0
    namespace: "{{ t_user_project }}"
  register: userprofile_build

- name: Create user profile build
  command: >-
          oc new-app -f "{{ ocp4_workload_servicemesh_workshop_userprofile_build_template }}" -n "{{ t_user_project }}" \
            -p APPLICATION_NAME=userprofile \
            -p APPLICATION_CODE_URI=https://github.com/RedHatGov/service-mesh-workshop-code.git \
            -p APPLICATION_CODE_BRANCH=workshop-stable \
            -p APP_VERSION_TAG=1.0
  when: userprofile_build.resources | length | int < 1

- name: Check if user profile was created already
  k8s_info:
    api_version: apps/v1
    kind: Deployment
    name: userprofile
    namespace: "{{ t_user_project }}"
  register: userprofile_deployment

- name: Start user profile build
  command: oc start-build userprofile-1.0 -n "{{ t_user_project }}"
  when: userprofile_deployment.resources | length | int < 1

- name: Wait until build is complete
  when: userprofile_deployment.resources | length | int < 1
  k8s_info:
    api_version: image.openshift.io/v1
    kind: ImageStream
    name: userprofile
    namespace: "{{ t_user_project }}"
  register: r_image_stream
  retries: 30
  delay: 5
  until:
  - r_image_stream.resources[0].status.dockerImageRepository is defined
  - r_image_stream.resources[0].status.dockerImageRepository | length > 0

- name: Deploy user profile
  when: userprofile_deployment.resources | length | int < 1
  k8s:
    state: present
    definition: "{{ lookup('template', './templates/userprofile.j2') }}"
  vars:
    userprofile_image_id: "{{ r_image_stream.resources[0].status.dockerImageRepository }}"

# Leave this as the last task in the playbook.
- name: workload tasks complete
  debug:
    msg: "Workload Tasks completed successfully."
  when: not silent | bool