---
## FRAMEWORK variables - do not change.
become_override: false
ocp_username: opentlc-mgr
silent: false

## ADD Variables here for use in your role, if needed.
## When you go to create a ServiceNow ticket to create 
## the RHPDS catalog item, you can ask the engineer to feed
## values the requesting user enters in the form in RHPDS
## into these variables. Everything you add here should be
## prefixed with the role name: ocp4_workload_servicemesh_workshop_*

## Workshop Settings
ocp4_workload_servicemesh_workshop_user_count: 1
ocp4_workload_servicemesh_workshop_image_repo: quay.io/redhatgov/service-mesh-workshop-dashboard
ocp4_workload_servicemesh_workshop_image_tag: "2.1-mini"

## Mini Workshop Settings
ocp4_workload_servicemesh_workshop_app_template: https://raw.githubusercontent.com/RedHatGov/service-mesh-workshop-code/workshop-stable/config/app/app-ui-fromsource.yaml
ocp4_workload_servicemesh_workshop_boards_template: https://raw.githubusercontent.com/RedHatGov/service-mesh-workshop-code/workshop-stable/config/app/boards-fromsource.yaml
ocp4_workload_servicemesh_workshop_context_scraper_template: https://raw.githubusercontent.com/RedHatGov/service-mesh-workshop-code/workshop-stable/config/app/context-scraper-fromsource.yaml
ocp4_workload_servicemesh_workshop_userprofile_build_template: https://raw.githubusercontent.com/RedHatGov/service-mesh-workshop-code/workshop-stable/config/app/userprofile-build.yaml

## Operator Settings
ocp4_workload_servicemesh_workshop_elasticsearch_channel: "4.6"
ocp4_workload_servicemesh_workshop_jaeger_channel: stable
ocp4_workload_servicemesh_workshop_kiali_channel: stable
ocp4_workload_servicemesh_workshop_servicemesh_channel: stable
ocp4_workload_servicemesh_workshop_rhsso_channel: alpha
ocp4_workload_servicemesh_workshop_elasticsearch_starting_csv: "elasticsearch-operator.4.6.0-202103010126.p0"
ocp4_workload_servicemesh_workshop_jaeger_starting_csv: "jaeger-operator.v1.20.3"
ocp4_workload_servicemesh_workshop_kiali_starting_csv: "kiali-operator.v1.24.7"
ocp4_workload_servicemesh_workshop_servicemesh_starting_csv: "servicemeshoperator.v2.0.5"
ocp4_workload_servicemesh_workshop_rhsso_starting_csv: "rhsso-operator.7.4.7"

## Operator Catalog Snapshot Settings
ocp4_workload_servicemesh_workshop_catalogsource_name: redhat-operators-snapshot-servicemesh-workshop
ocp4_workload_servicemesh_workshop_catalog_snapshot_image: quay.io/jakang/olm_snapshot_redhat_catalog
ocp4_workload_servicemesh_workshop_catalog_snapshot_image_tag: "v4.6_2021_05_23"
